# haneling pull request by label
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
    condetion: |
      - any (contains (github.event.pull_request.title, 'bug'))

  - name: feature
    color: 0e8a16
    description: New feature or request
    condetion: |
      - any (contains (github.event.pull_request.title, 'feature'), contains (github.event.pull_request.title, 'feat'))

  - name: fix
    color: 0e8a16
    description: Fixing a bug
    condetion: |
      - any (contains (github.event.pull_request.title, 'fix'))
