name: Last-TRY

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.INSTANCE_IP }}
          REMOTE_USER: ${{ secrets.INSTANCE_USER }}
          REMOTE_PORT: ${{ secrets.INSTANCE_PORT}}
      - name: building the app
        uses: appleboy/ssh-action@master
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USER }}
          script: |
            yarn/npm install
            yarn/npm build
