name: Deploy to EC2 New

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build client and server
        run: |
          yarn build-server

      - name: Deploy to EC2
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} -r ./dist/apps ${{ secrets.INSTANCE_USER }}@${{ secrets.INSTANCE_HOST }}:/home/ubuntu/my-nx-project

      - name: Restart server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.INSTANCE_USER }}@${{ secrets.INSTANCE_HOST }} "sudo systemctl restart my-nx-project-server.service"
