name: Deploy to EC2 New

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build client and server
        run: |
          yarn build-server

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2.1.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.INSTANCE_HOST}}
          REMOTE_USER: ${{ secrets.INSTANCE_USER }}
          TARGET: "/home/ecs-user/AlManshaah"
          SOURCE: "./dist/apps"
        with:
          args: "-rltgoDzvO --delete"

      - name: Restart server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.INSTANCE_USER }}@${{ secrets.INSTANCE_HOST }} "sudo systemctl restart AlManshaah-server.service"
