name: Deploy to EC2 New

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build client and server
        run: |
          yarn build-server

      - name: Deploy to EC2
        uses: appleboy/scp-action@main
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          username: ${{ secrets.INSTANCE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          source: 'dist/apps/workspace'
          target: '/home/ubuntu/workspace'

