name: Ec2-Prod
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install Yarn
        run: sudo npm install -g yarn
      - name: Checking ssh-agent
        run: eval "$(ssh-agent -s)"
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copy files to instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: /home/ubuntu/Al-Manshaah
      - name: Connect to instance and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.INSTANCE_PORT }}
          script: |
            cd /home/ec2-user/my-app
            yarn
            npx nx format:check
            npx nx affected --target=lint --parallel=3
            npx nx affected --target=test --parallel=3 --configuration=ci
            npx nx affected --target=build --parallel=3
