name: Pull Request Labeling

on:
  - pull_request
permissions:
  contents: read
  pull-requests: write

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const labels = github.event.head.commit.message.split(':')
            const label = labels[0].trim()
            const pr = context.payload.pull_request
            const issue_number = pr.number
            const owner = context.repo.owner
            const repo = context.repo.repo
            const params = { owner, repo, issue_number, labels: [label] }
            await github.issues.addLabels(params)
