name: Pull Request Labeling

on:
  - pull_request
permissions:
  contents: read
  pull-requests: write

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const lastCommit = context.payload.pull_request.commits_url.split(':').pop()
            const { data: commits } = await github.request(context.payload.pull_request.commits_url)
            const { data: files } = await github.request(commits[commits.length - 1].url)
            const labels = files.map(file => file.filename.split(':')[0]).filter((value, index, self) => self.indexOf(value) === index)
            await github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels 
            })
