name: Pull Request Labeling

on:
  - pull_request
permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  #  add label from the semantic title of the PR (e.g. feat: add label to PR)

  add-label-to-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/semantic.yml
