name: Pull Request Labeling

on:
  - pull_request
permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  #  add label to pr by the semantic versioning of the pr title

  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          script: |
            const title = context.payload.pull_request.title;
            const label = title.startsWith('feat') ? 'feature' : title.startsWith('fix') ? 'bug' : 'other';
            await github.issues.addLabels({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              labels: [label],
            });
