name: Pull Request Labeling

on:
  - pull_request
permissions:
  contents: read
  pull-requests: write

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const labels = github.event.pull_request.labels.map(label => label.name)
            if (labels.includes('feature') || labels.includes('feat')) {
              github.issues.addLabels({
                issue_number: github.event.number,
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                labels: ['feature'],
                color: 'green'
              })
              else if (labels.includes('bug')) {
              github.issues.addLabels({
                issue_number: github.event.number,
                owner: github.context.repo.owner,
                repo: github.context.repo.repo,
                labels: ['bug'],
                color: 'red'
              })
            })
